
epg:
  merchantSite: http://localhost:8080
  api: https://uat.api.converge.eu.elavonaws.com
  hpp: https://uat.hpp.converge.eu.elavonaws.com

  # global testing credentials for limited testing.  see the readme for instructions on replacing these
  merchantAlias: 3fk6thcgh84rqvqtfvyvv4cbbd26
  secretKey: sk_79rhqg2ftmgwrc4xgyj9cr4ccwxp
  publicApiKey: pk_ph4v9y6ccjd3kw2pff4fdxxhbdy6

---
spring:
  config:
    activate:
      on-profile: prod

epg:
  api: https://api.eu.convergepay.com
  hpp: https://hpp.eu.convergepay.com
---

---
spring:
  config:
    activate:
      on-profile: debug
logging:
  level:
    org.apache.http.wire: DEBUG




